name: mango-api

include:
  - path: ./docker/compose.postgres.yml
    env_file: .env.local
  - path: ./docker/compose.redis.yml
    env_file: .env.local

volumes:
  mango-data:
    driver: local
    name: mango-data
  redis-data:
    driver: local
    name: redis-data

networks:
  mango-network:
    driver: bridge
    name: mango-network
