name: mango

include:
  - path: ./server/compose.yml

volumes:
  mango-data:
    driver: local
    name: mango-data
  redis-data:
    driver: local
    name: redis-data

networks:
  mango-network:
    driver: bridge
    name: mango-network
