name: mango-api

include:
  - path: ./docker/redis.compose.yml
  - path: ./docker/postgres.compose.yml

volumes:
  mango-pg-data:
    driver: local
    name: mango-pg-data
  mango-redis-data:
    driver: local
    name: mango-redis-data

networks:
  mango-network:
    driver: bridge
    name: mango-network
