-- Room 1: the-trio (Donald, Jagger, Deidad)
INSERT INTO mango.messages (content, "senderId", "roomId") VALUES
  ('Hey guys! How was your weekend?', 1, 1),
  ('Pretty chill, just watched some movies. You?', 2, 1),
  ('Same here, nothing special', 3, 1),
  ('I went hiking on Saturday, the weather was perfect', 1, 1),
  ('That sounds awesome! Where did you go?', 2, 1),
  ('Blue Ridge Trail, about 2 hours from here', 1, 1),
  ('Oh I know that place, love it there', 3, 1),
  ('We should all go together sometime', 2, 1),
  ('Definitely! Next weekend maybe?', 1, 1),
  ('I''m in!', 3, 1),
  ('Count me in too', 2, 1),
  ('Perfect, I''ll check the forecast and let you know', 1, 1),
  ('Sounds good!', 3, 1),
  ('Can''t wait', 2, 1),
  ('By the way, did anyone watch the game last night?', 3, 1),

-- Room 2: quad-squad (Jagger, Donald, Mystic, Supreme)
  ('Good morning team!', 2, 2),
  ('Morning! Ready for the week ahead?', 1, 2),
  ('Hey everyone!', 4, 2),
  ('Morning all', 5, 2),
  ('So I was thinking we should finalize the project timeline today', 2, 2),
  ('Good idea. What are the main milestones?', 1, 2),
  ('We need to have the design done by Friday', 2, 2),
  ('That''s doable. I can have my part ready by Thursday', 4, 2),
  ('Same here', 5, 2),
  ('Great! What about the development phase?', 2, 2),
  ('I think we need at least two weeks for that', 1, 2),
  ('Agreed. That gives us buffer time for testing', 4, 2),
  ('Perfect. So we''re looking at end of month delivery?', 2, 2),
  ('Yep, that should work', 5, 2),
  ('Awesome. I''ll update the timeline doc', 2, 2),
  ('Thanks for organizing this', 1, 2),
  ('No problem! By the way, are we meeting tomorrow?', 2, 2),
  ('Yes, 10 AM right?', 4, 2),
  ('Correct. Conference room B', 2, 2),
  ('I''ll bring coffee', 5, 2),
  ('You''re a legend', 1, 2),
  ('Anyone need anything else?', 2, 2),
  ('I think we''re good', 4, 2),
  ('All set here', 5, 2),
  ('Alright, see you all tomorrow then!', 2, 2),

-- Room 3: all-stars (Deidad, Donald, Jagger, Mystic was LEAVED, Supreme)
  ('Hello everyone!', 3, 3),
  ('Hey! What''s up?', 1, 3),
  ('Just working on some stuff', 2, 3),
  ('Hey team, I have an announcement', 3, 3),
  ('What''s going on?', 5, 3),
  ('We''re organizing a meetup next month!', 3, 3),
  ('That''s exciting! Where?', 1, 3),
  ('Downtown convention center', 3, 3),
  ('I can definitely make it', 2, 3),
  ('Same! What''s the date?', 5, 3),
  ('Looking at the 15th or 16th', 3, 3),
  ('15th works better for me', 1, 3),
  ('Me too', 2, 3),
  ('15th it is then!', 3, 3),
  ('What should we prepare?', 5, 3),
  ('I''ll send an agenda by end of week', 3, 3),
  ('Perfect', 1, 3),
  ('Also, we should discuss the new features', 2, 3),
  ('Yes! I have some ideas to share', 5, 3),
  ('Let''s add that to the agenda', 3, 3),
  ('Sounds good to me', 1, 3),
  ('Quick question - what about accommodation?', 2, 3),
  ('There are a few hotels nearby, I''ll share a list', 3, 3),
  ('Thanks! That would be helpful', 5, 3),
  ('No worries', 3, 3),
  ('By the way, how''s everyone''s progress on their tasks?', 1, 3),
  ('Mine''s going well, about 70% done', 2, 3),
  ('Almost finished here, should wrap up tomorrow', 5, 3),
  ('Great work everyone!', 3, 3),
  ('Thanks!', 1, 3),
  ('Appreciate it', 2, 3),
  ('Quick reminder: deadline is Friday', 3, 3),
  ('Got it!', 5, 3),
  ('All good here', 1, 3),
  ('Excellent. Anything else we need to discuss?', 3, 3),
  ('I think we''re covered', 2, 3),

-- Room 4: duo (Mystic, Supreme)
  ('Hey! Got a minute?', 4, 4),
  ('Sure, what''s up?', 5, 4),
  ('I wanted to run something by you', 4, 4),
  ('Go ahead', 5, 4),
  ('I''m thinking about switching to the new framework', 4, 4),
  ('Interesting. Any particular reason?', 5, 4),
  ('Better performance and cleaner code', 4, 4),
  ('Makes sense. When are you planning to start?', 5, 4),
  ('Next sprint probably', 4, 4),
  ('Need any help with the migration?', 5, 4),
  ('That would be great! Maybe we can pair on it?', 4, 4),
  ('Absolutely! Just let me know when', 5, 4);
